
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pskishere/xpress
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    environment:
      - YARN_ONLY=true
      - NODE_PATH=/app/node_modules

  news-sync:
    build:
      context: .
      dockerfile: Dockerfile.news-sync
    image: pskishere/xpress-sync
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    environment:
      - YARN_ONLY=true
      - NODE_PATH=/app/node_modules

volumes:
  node_modules:
