version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    command: >
      sh -c "
        npm run start &
        echo '0 0,12 * * * /usr/local/bin/node /app/src/utils/syncNews.js >> /var/log/cron.log 2>&1' > /etc/cron.d/news-sync-cron
        chmod 0644 /etc/cron.d/news-sync-cron
        crontab /etc/cron.d/news-sync-cron
        cron -f"

volumes:
  node_modules:
