version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    environment:
      - VITE_SUPABASE_PROJECT_URL=${VITE_SUPABASE_PROJECT_URL}
      - VITE_SUPABASE_API_KEY=${VITE_SUPABASE_API_KEY}

  news-sync:
    build:
      context: .
      dockerfile: Dockerfile.news-sync
    restart: unless-stopped
    environment:
      - VITE_SUPABASE_PROJECT_URL=${VITE_SUPABASE_PROJECT_URL}
      - VITE_SUPABASE_API_KEY=${VITE_SUPABASE_API_KEY}
    volumes:
      - ./src:/app/src

volumes:
  node_modules:
