
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pskishere/xpress
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    environment:
      - YARN_ONLY=true

  news-sync:
    build:
      context: .
      dockerfile: Dockerfile.news-sync
    image: pskishere/xpress-sync
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    environment:
      - YARN_ONLY=true

volumes:
  node_modules:
