version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  news-sync:
    build: 
      context: .
      dockerfile: Dockerfile
    command: node src/utils/syncNews.js
    restart: on-failure
    depends_on:
      - app

volumes:
  node_modules:
